version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  web:
    build: .
    command: gunicorn --timeout 120 -w 4 -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    depends_on:
      - db
